//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/authreturn-v2")]
public partial class PublicKeyInfoType {
    
    private System.DateTime expirydateField;
    
    private string urlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expiry-date")]
    public System.DateTime expirydate {
        get {
            return this.expirydateField;
        }
        set {
            this.expirydateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/authreturn-v2")]
public partial class NotificationsType {
    
    private NotificationsTypeNotification[] notificationField;
    
    private NotificationsTypeEmailsubject emailsubjectField;
    
    private bool emailsubjectFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("notification")]
    public NotificationsTypeNotification[] notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("email-subject")]
    public NotificationsTypeEmailsubject emailsubject {
        get {
            return this.emailsubjectField;
        }
        set {
            this.emailsubjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool emailsubjectSpecified {
        get {
            return this.emailsubjectFieldSpecified;
        }
        set {
            this.emailsubjectFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/authreturn-v2")]
public partial class NotificationsTypeNotification {
    
    private string emailField;
    
    private bool onshipmentField;
    
    private bool onexceptionField;
    
    private bool ondeliveryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("on-shipment")]
    public bool onshipment {
        get {
            return this.onshipmentField;
        }
        set {
            this.onshipmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("on-exception")]
    public bool onexception {
        get {
            return this.onexceptionField;
        }
        set {
            this.onexceptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("on-delivery")]
    public bool ondelivery {
        get {
            return this.ondeliveryField;
        }
        set {
            this.ondeliveryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/authreturn-v2")]
public enum NotificationsTypeEmailsubject {
    
    /// <remarks/>
    tracking,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("customer-ref-1")]
    customerref1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("customer-ref-2")]
    customerref2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/authreturn-v2")]
public partial class AuthSettlementInfoType {
    
    private string paidbycustomerField;
    
    private string contractidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("paid-by-customer")]
    public string paidbycustomer {
        get {
            return this.paidbycustomerField;
        }
        set {
            this.paidbycustomerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contract-id")]
    public string contractid {
        get {
            return this.contractidField;
        }
        set {
            this.contractidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/authreturn-v2")]
public partial class ReceiverType {
    
    private string nameField;
    
    private string companyField;
    
    private string emailField;
    
    private string receivervoicenumberField;
    
    private DomesticAddressDetailsType domesticaddressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("receiver-voice-number", DataType="normalizedString")]
    public string receivervoicenumber {
        get {
            return this.receivervoicenumberField;
        }
        set {
            this.receivervoicenumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("domestic-address")]
    public DomesticAddressDetailsType domesticaddress {
        get {
            return this.domesticaddressField;
        }
        set {
            this.domesticaddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/authreturn-v2")]
public partial class ReturnerType {
    
    private string nameField;
    
    private string companyField;
    
    private DomesticAddressDetailsType domesticaddressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("domestic-address")]
    public DomesticAddressDetailsType domesticaddress {
        get {
            return this.domesticaddressField;
        }
        set {
            this.domesticaddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/authreturn-v2")]
[System.Xml.Serialization.XmlRootAttribute("authorized-return", Namespace="http://www.canadapost.ca/ws/authreturn-v2", IsNullable=false)]
public partial class AuthorizedReturnType {
    
    private bool createpublickeyField;
    
    private bool createpublickeyFieldSpecified;
    
    private string servicecodeField;
    
    private ReturnerType returnerField;
    
    private ReceiverType receiverField;
    
    private ParcelCharacteristicsType parcelcharacteristicsField;
    
    private PrintPreferencesType printpreferencesField;
    
    private AuthSettlementInfoType settlementinfoField;
    
    private ReferencesType referencesField;
    
    private NotificationsType notificationsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("create-public-key")]
    public bool createpublickey {
        get {
            return this.createpublickeyField;
        }
        set {
            this.createpublickeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool createpublickeySpecified {
        get {
            return this.createpublickeyFieldSpecified;
        }
        set {
            this.createpublickeyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-code", DataType="normalizedString")]
    public string servicecode {
        get {
            return this.servicecodeField;
        }
        set {
            this.servicecodeField = value;
        }
    }
    
    /// <remarks/>
    public ReturnerType returner {
        get {
            return this.returnerField;
        }
        set {
            this.returnerField = value;
        }
    }
    
    /// <remarks/>
    public ReceiverType receiver {
        get {
            return this.receiverField;
        }
        set {
            this.receiverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parcel-characteristics")]
    public ParcelCharacteristicsType parcelcharacteristics {
        get {
            return this.parcelcharacteristicsField;
        }
        set {
            this.parcelcharacteristicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("print-preferences")]
    public PrintPreferencesType printpreferences {
        get {
            return this.printpreferencesField;
        }
        set {
            this.printpreferencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("settlement-info")]
    public AuthSettlementInfoType settlementinfo {
        get {
            return this.settlementinfoField;
        }
        set {
            this.settlementinfoField = value;
        }
    }
    
    /// <remarks/>
    public ReferencesType references {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    public NotificationsType notifications {
        get {
            return this.notificationsField;
        }
        set {
            this.notificationsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/authreturn-v2")]
[System.Xml.Serialization.XmlRootAttribute("authorized-return-info", Namespace="http://www.canadapost.ca/ws/authreturn-v2", IsNullable=false)]
public partial class AuthorizedReturnInfoType {
    
    private string trackingpinField;
    
    private PublicKeyInfoType publickeyinfoField;
    
    private LinkType[] linksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tracking-pin", DataType="normalizedString")]
    public string trackingpin {
        get {
            return this.trackingpinField;
        }
        set {
            this.trackingpinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("public-key-info")]
    public PublicKeyInfoType publickeyinfo {
        get {
            return this.publickeyinfoField;
        }
        set {
            this.publickeyinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable=false)]
    public LinkType[] links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
}
