//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/customer")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.canadapost.ca/ws/customer", IsNullable=false)]
public partial class customer : CustomerBaseType {
    
    private LinkType[] linksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable=false)]
    public LinkType[] links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/customer")]
public enum RelType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("behalf-of-customer")]
    behalfofcustomer,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/customer")]
public partial class PayerType {
    
    private string payernumberField;
    
    private string[] methodsofpaymentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("payer-number", DataType="normalizedString")]
    public string payernumber {
        get {
            return this.payernumberField;
        }
        set {
            this.payernumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("methods-of-payment")]
    [System.Xml.Serialization.XmlArrayItemAttribute("method-of-payment", DataType="normalizedString", IsNullable=false)]
    public string[] methodsofpayment {
        get {
            return this.methodsofpaymentField;
        }
        set {
            this.methodsofpaymentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/customer")]
public partial class CustomerBaseType {
    
    private string customernumberField;
    
    private string[] contractsField;
    
    private PayerType[] authorizedpayersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-number")]
    public string customernumber {
        get {
            return this.customernumberField;
        }
        set {
            this.customernumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("contract-id", IsNullable=false)]
    public string[] contracts {
        get {
            return this.contractsField;
        }
        set {
            this.contractsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("authorized-payers")]
    [System.Xml.Serialization.XmlArrayItemAttribute("payer", IsNullable=false)]
    public PayerType[] authorizedpayers {
        get {
            return this.authorizedpayersField;
        }
        set {
            this.authorizedpayersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/customer")]
[System.Xml.Serialization.XmlRootAttribute("behalf-of-customer", Namespace="http://www.canadapost.ca/ws/customer", IsNullable=false)]
public partial class behalfofcustomer : CustomerBaseType {
}
