//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/manifest-v8")]
public partial class ManifestPricingInfoType {
    
    private decimal basecostField;
    
    private decimal automationdiscountField;
    
    private decimal optionsandsurchargesField;
    
    private decimal gstField;
    
    private decimal pstField;
    
    private decimal hstField;
    
    private decimal totalduecpcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("base-cost")]
    public decimal basecost {
        get {
            return this.basecostField;
        }
        set {
            this.basecostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("automation-discount")]
    public decimal automationdiscount {
        get {
            return this.automationdiscountField;
        }
        set {
            this.automationdiscountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("options-and-surcharges")]
    public decimal optionsandsurcharges {
        get {
            return this.optionsandsurchargesField;
        }
        set {
            this.optionsandsurchargesField = value;
        }
    }
    
    /// <remarks/>
    public decimal gst {
        get {
            return this.gstField;
        }
        set {
            this.gstField = value;
        }
    }
    
    /// <remarks/>
    public decimal pst {
        get {
            return this.pstField;
        }
        set {
            this.pstField = value;
        }
    }
    
    /// <remarks/>
    public decimal hst {
        get {
            return this.hstField;
        }
        set {
            this.hstField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("total-due-cpc")]
    public decimal totalduecpc {
        get {
            return this.totalduecpcField;
        }
        set {
            this.totalduecpcField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/manifest-v8")]
public partial class ManifestAddressType {
    
    private string manifestcompanyField;
    
    private string manifestnameField;
    
    private string phonenumberField;
    
    private ManifestAddressDetailsType addressdetailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("manifest-company", DataType="normalizedString")]
    public string manifestcompany {
        get {
            return this.manifestcompanyField;
        }
        set {
            this.manifestcompanyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("manifest-name", DataType="normalizedString")]
    public string manifestname {
        get {
            return this.manifestnameField;
        }
        set {
            this.manifestnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("phone-number", DataType="normalizedString")]
    public string phonenumber {
        get {
            return this.phonenumberField;
        }
        set {
            this.phonenumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("address-details")]
    public ManifestAddressDetailsType addressdetails {
        get {
            return this.addressdetailsField;
        }
        set {
            this.addressdetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/manifest-v8")]
[System.Xml.Serialization.XmlRootAttribute("transmit-set", Namespace="http://www.canadapost.ca/ws/manifest-v8", IsNullable=false)]
public partial class ShipmentTransmitSetType {
    
    private string customerrequestidField;
    
    private string[] groupidsField;
    
    private bool cpcpickupindicatorField;
    
    private bool cpcpickupindicatorFieldSpecified;
    
    private string requestedshippingpointField;
    
    private string shippingpointidField;
    
    private bool detailedmanifestsField;
    
    private string methodofpaymentField;
    
    private ManifestAddressType manifestaddressField;
    
    private string customerreferenceField;
    
    private string[] excludedshipmentsField;
    
    public ShipmentTransmitSetType() {
        this.cpcpickupindicatorField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-request-id", DataType="normalizedString")]
    public string customerrequestid {
        get {
            return this.customerrequestidField;
        }
        set {
            this.customerrequestidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("group-ids")]
    [System.Xml.Serialization.XmlArrayItemAttribute("group-id", DataType="normalizedString", IsNullable=false)]
    public string[] groupids {
        get {
            return this.groupidsField;
        }
        set {
            this.groupidsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cpc-pickup-indicator")]
    public bool cpcpickupindicator {
        get {
            return this.cpcpickupindicatorField;
        }
        set {
            this.cpcpickupindicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cpcpickupindicatorSpecified {
        get {
            return this.cpcpickupindicatorFieldSpecified;
        }
        set {
            this.cpcpickupindicatorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("requested-shipping-point")]
    public string requestedshippingpoint {
        get {
            return this.requestedshippingpointField;
        }
        set {
            this.requestedshippingpointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-point-id", DataType="normalizedString")]
    public string shippingpointid {
        get {
            return this.shippingpointidField;
        }
        set {
            this.shippingpointidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("detailed-manifests")]
    public bool detailedmanifests {
        get {
            return this.detailedmanifestsField;
        }
        set {
            this.detailedmanifestsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("method-of-payment", DataType="normalizedString")]
    public string methodofpayment {
        get {
            return this.methodofpaymentField;
        }
        set {
            this.methodofpaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("manifest-address")]
    public ManifestAddressType manifestaddress {
        get {
            return this.manifestaddressField;
        }
        set {
            this.manifestaddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-reference")]
    public string customerreference {
        get {
            return this.customerreferenceField;
        }
        set {
            this.customerreferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("excluded-shipments")]
    [System.Xml.Serialization.XmlArrayItemAttribute("shipment-id", DataType="normalizedString", IsNullable=false)]
    public string[] excludedshipments {
        get {
            return this.excludedshipmentsField;
        }
        set {
            this.excludedshipmentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/manifest-v8")]
[System.Xml.Serialization.XmlRootAttribute("manifests", Namespace="http://www.canadapost.ca/ws/manifest-v8", IsNullable=false)]
public partial class ManifestsType {
    
    private LinkType[] linkField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link")]
    public LinkType[] link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/manifest-v8")]
[System.Xml.Serialization.XmlRootAttribute("manifest", Namespace="http://www.canadapost.ca/ws/manifest-v8", IsNullable=false)]
public partial class ManifestType {
    
    private string customerrequestidField;
    
    private string ponumberField;
    
    private LinkType[] linksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-request-id", DataType="normalizedString")]
    public string customerrequestid {
        get {
            return this.customerrequestidField;
        }
        set {
            this.customerrequestidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-number")]
    public string ponumber {
        get {
            return this.ponumberField;
        }
        set {
            this.ponumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable=false)]
    public LinkType[] links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/manifest-v8")]
[System.Xml.Serialization.XmlRootAttribute("manifest-details", Namespace="http://www.canadapost.ca/ws/manifest-v8", IsNullable=false)]
public partial class ManifestDetailsType {
    
    private string ponumberField;
    
    private string finalshippingpointField;
    
    private string shippingpointnameField;
    
    private string shippingpointidField;
    
    private bool cpcpickupindicatorField;
    
    private bool cpcpickupindicatorFieldSpecified;
    
    private string mailedbycustomerField;
    
    private string mailedonbehalfofField;
    
    private string paidbycustomerField;
    
    private string customerrefField;
    
    private System.DateTime manifestdateField;
    
    private string manifesttimeField;
    
    private string contractidField;
    
    private string methodofpaymentField;
    
    private ManifestDetailsTypeCcreceiptdetails ccreceiptdetailsField;
    
    private ManifestDetailsTypeSupplieraccountreceiptdetails supplieraccountreceiptdetailsField;
    
    private ManifestPricingInfoType manifestpricinginfoField;
    
    private ManifestAddressType manifestaddressField;
    
    public ManifestDetailsType() {
        this.cpcpickupindicatorField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-number")]
    public string ponumber {
        get {
            return this.ponumberField;
        }
        set {
            this.ponumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("final-shipping-point")]
    public string finalshippingpoint {
        get {
            return this.finalshippingpointField;
        }
        set {
            this.finalshippingpointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-point-name", DataType="normalizedString")]
    public string shippingpointname {
        get {
            return this.shippingpointnameField;
        }
        set {
            this.shippingpointnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-point-id", DataType="normalizedString")]
    public string shippingpointid {
        get {
            return this.shippingpointidField;
        }
        set {
            this.shippingpointidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cpc-pickup-indicator")]
    public bool cpcpickupindicator {
        get {
            return this.cpcpickupindicatorField;
        }
        set {
            this.cpcpickupindicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cpcpickupindicatorSpecified {
        get {
            return this.cpcpickupindicatorFieldSpecified;
        }
        set {
            this.cpcpickupindicatorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mailed-by-customer")]
    public string mailedbycustomer {
        get {
            return this.mailedbycustomerField;
        }
        set {
            this.mailedbycustomerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mailed-on-behalf-of")]
    public string mailedonbehalfof {
        get {
            return this.mailedonbehalfofField;
        }
        set {
            this.mailedonbehalfofField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("paid-by-customer")]
    public string paidbycustomer {
        get {
            return this.paidbycustomerField;
        }
        set {
            this.paidbycustomerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-ref", DataType="normalizedString")]
    public string customerref {
        get {
            return this.customerrefField;
        }
        set {
            this.customerrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("manifest-date", DataType="date")]
    public System.DateTime manifestdate {
        get {
            return this.manifestdateField;
        }
        set {
            this.manifestdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("manifest-time", DataType="normalizedString")]
    public string manifesttime {
        get {
            return this.manifesttimeField;
        }
        set {
            this.manifesttimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contract-id")]
    public string contractid {
        get {
            return this.contractidField;
        }
        set {
            this.contractidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("method-of-payment", DataType="normalizedString")]
    public string methodofpayment {
        get {
            return this.methodofpaymentField;
        }
        set {
            this.methodofpaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cc-receipt-details")]
    public ManifestDetailsTypeCcreceiptdetails ccreceiptdetails {
        get {
            return this.ccreceiptdetailsField;
        }
        set {
            this.ccreceiptdetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("supplier-account-receipt-details")]
    public ManifestDetailsTypeSupplieraccountreceiptdetails supplieraccountreceiptdetails {
        get {
            return this.supplieraccountreceiptdetailsField;
        }
        set {
            this.supplieraccountreceiptdetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("manifest-pricing-info")]
    public ManifestPricingInfoType manifestpricinginfo {
        get {
            return this.manifestpricinginfoField;
        }
        set {
            this.manifestpricinginfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("manifest-address")]
    public ManifestAddressType manifestaddress {
        get {
            return this.manifestaddressField;
        }
        set {
            this.manifestaddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/manifest-v8")]
public partial class ManifestDetailsTypeCcreceiptdetails {
    
    private string merchantnameField;
    
    private string merchanturlField;
    
    private string nameoncardField;
    
    private string authcodeField;
    
    private System.DateTime authtimestampField;
    
    private CcType cardtypeField;
    
    private string currencyField;
    
    private string transactiontypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-name", DataType="normalizedString")]
    public string merchantname {
        get {
            return this.merchantnameField;
        }
        set {
            this.merchantnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-url", DataType="normalizedString")]
    public string merchanturl {
        get {
            return this.merchanturlField;
        }
        set {
            this.merchanturlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name-on-card", DataType="normalizedString")]
    public string nameoncard {
        get {
            return this.nameoncardField;
        }
        set {
            this.nameoncardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-code", DataType="normalizedString")]
    public string authcode {
        get {
            return this.authcodeField;
        }
        set {
            this.authcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-timestamp")]
    public System.DateTime authtimestamp {
        get {
            return this.authtimestampField;
        }
        set {
            this.authtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("card-type")]
    public CcType cardtype {
        get {
            return this.cardtypeField;
        }
        set {
            this.cardtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transaction-type", DataType="normalizedString")]
    public string transactiontype {
        get {
            return this.transactiontypeField;
        }
        set {
            this.transactiontypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/manifest-v8")]
public partial class ManifestDetailsTypeSupplieraccountreceiptdetails {
    
    private string merchantnameField;
    
    private string merchanturlField;
    
    private string authcodeField;
    
    private System.DateTime authtimestampField;
    
    private string supplieridField;
    
    private string currencyField;
    
    private string transactiontypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-name", DataType="normalizedString")]
    public string merchantname {
        get {
            return this.merchantnameField;
        }
        set {
            this.merchantnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-url", DataType="normalizedString")]
    public string merchanturl {
        get {
            return this.merchanturlField;
        }
        set {
            this.merchanturlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-code", DataType="normalizedString")]
    public string authcode {
        get {
            return this.authcodeField;
        }
        set {
            this.authcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-timestamp")]
    public System.DateTime authtimestamp {
        get {
            return this.authtimestampField;
        }
        set {
            this.authtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("supplier-id", DataType="normalizedString")]
    public string supplierid {
        get {
            return this.supplieridField;
        }
        set {
            this.supplieridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transaction-type", DataType="normalizedString")]
    public string transactiontype {
        get {
            return this.transactiontypeField;
        }
        set {
            this.transactiontypeField = value;
        }
    }
}
