//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
[System.Xml.Serialization.XmlRootAttribute("pickup-request-details", Namespace="http://www.canadapost.ca/ws/pickuprequest", IsNullable=false)]
public partial class PickupRequestDetailsType {
    
    private string customerrequestidField;
    
    private PickupTypeType pickuptypeField;
    
    private PickupLocationType pickuplocationField;
    
    private ContactInfoType contactinfoField;
    
    private LocationDetailsType locationdetailsField;
    
    private ItemsCharacteristicsType itemscharacteristicsField;
    
    private string pickupvolumeField;
    
    private PickupTimesType pickuptimesField;
    
    private PaymentInfoType paymentinfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-request-id", DataType="normalizedString")]
    public string customerrequestid {
        get {
            return this.customerrequestidField;
        }
        set {
            this.customerrequestidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-type")]
    public PickupTypeType pickuptype {
        get {
            return this.pickuptypeField;
        }
        set {
            this.pickuptypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-location")]
    public PickupLocationType pickuplocation {
        get {
            return this.pickuplocationField;
        }
        set {
            this.pickuplocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contact-info")]
    public ContactInfoType contactinfo {
        get {
            return this.contactinfoField;
        }
        set {
            this.contactinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("location-details")]
    public LocationDetailsType locationdetails {
        get {
            return this.locationdetailsField;
        }
        set {
            this.locationdetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("items-characteristics")]
    public ItemsCharacteristicsType itemscharacteristics {
        get {
            return this.itemscharacteristicsField;
        }
        set {
            this.itemscharacteristicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-volume", DataType="normalizedString")]
    public string pickupvolume {
        get {
            return this.pickupvolumeField;
        }
        set {
            this.pickupvolumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-times")]
    public PickupTimesType pickuptimes {
        get {
            return this.pickuptimesField;
        }
        set {
            this.pickuptimesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("payment-info")]
    public PaymentInfoType paymentinfo {
        get {
            return this.paymentinfoField;
        }
        set {
            this.paymentinfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public enum PickupTypeType {
    
    /// <remarks/>
    OnDemand,
    
    /// <remarks/>
    Scheduled,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class PickupLocationType {
    
    private bool businessaddressflagField;
    
    private AlternateAddressType alternateaddressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("business-address-flag")]
    public bool businessaddressflag {
        get {
            return this.businessaddressflagField;
        }
        set {
            this.businessaddressflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("alternate-address")]
    public AlternateAddressType alternateaddress {
        get {
            return this.alternateaddressField;
        }
        set {
            this.alternateaddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class AlternateAddressType {
    
    private string companyField;
    
    private string addressline1Field;
    
    private string cityField;
    
    private string provinceField;
    
    private string postalcodeField;
    
    /// <remarks/>
    public string company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("address-line-1")]
    public string addressline1 {
        get {
            return this.addressline1Field;
        }
        set {
            this.addressline1Field = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("postal-code")]
    public string postalcode {
        get {
            return this.postalcodeField;
        }
        set {
            this.postalcodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class PickupRequestType {
    
    private PickupRequestHeaderType pickuprequestheaderField;
    
    private LinkType[] linksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-request-header")]
    public PickupRequestHeaderType pickuprequestheader {
        get {
            return this.pickuprequestheaderField;
        }
        set {
            this.pickuprequestheaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable=false)]
    public LinkType[] links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class PickupRequestHeaderType {
    
    private string requestidField;
    
    private PickupStatusType requeststatusField;
    
    private PickupTypeType pickuptypeField;
    
    private System.DateTime requestdateField;
    
    private bool requestdateFieldSpecified;
    
    private System.DateTime nextpickupdateField;
    
    private bool nextpickupdateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("request-id", DataType="normalizedString")]
    public string requestid {
        get {
            return this.requestidField;
        }
        set {
            this.requestidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("request-status")]
    public PickupStatusType requeststatus {
        get {
            return this.requeststatusField;
        }
        set {
            this.requeststatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-type")]
    public PickupTypeType pickuptype {
        get {
            return this.pickuptypeField;
        }
        set {
            this.pickuptypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("request-date", DataType="date")]
    public System.DateTime requestdate {
        get {
            return this.requestdateField;
        }
        set {
            this.requestdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool requestdateSpecified {
        get {
            return this.requestdateFieldSpecified;
        }
        set {
            this.requestdateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("next-pickup-date", DataType="date")]
    public System.DateTime nextpickupdate {
        get {
            return this.nextpickupdateField;
        }
        set {
            this.nextpickupdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nextpickupdateSpecified {
        get {
            return this.nextpickupdateFieldSpecified;
        }
        set {
            this.nextpickupdateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public enum PickupStatusType {
    
    /// <remarks/>
    Active,
    
    /// <remarks/>
    New,
    
    /// <remarks/>
    Cancelled,
    
    /// <remarks/>
    Pending,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Missed Pickup")]
    MissedPickup,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class ContactInfoResponseDetailsType {
    
    private string contactnameField;
    
    private string emailField;
    
    private string contactphoneField;
    
    private string telephoneextField;
    
    private bool receiveemailupdatesflagField;
    
    private bool receiveemailupdatesflagFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contact-name")]
    public string contactname {
        get {
            return this.contactnameField;
        }
        set {
            this.contactnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contact-phone", DataType="normalizedString")]
    public string contactphone {
        get {
            return this.contactphoneField;
        }
        set {
            this.contactphoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("telephone-ext", DataType="normalizedString")]
    public string telephoneext {
        get {
            return this.telephoneextField;
        }
        set {
            this.telephoneextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("receive-email-updates-flag")]
    public bool receiveemailupdatesflag {
        get {
            return this.receiveemailupdatesflagField;
        }
        set {
            this.receiveemailupdatesflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool receiveemailupdatesflagSpecified {
        get {
            return this.receiveemailupdatesflagFieldSpecified;
        }
        set {
            this.receiveemailupdatesflagFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class PickupRequestResponseDetailsType {
    
    private PickupLocationType pickuplocationField;
    
    private ContactInfoResponseDetailsType contactinfoField;
    
    private LocationDetailsType locationdetailsField;
    
    private ItemsCharacteristicsType itemscharacteristicsField;
    
    private string pickupvolumeField;
    
    private PickupTimesType pickuptimesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-location")]
    public PickupLocationType pickuplocation {
        get {
            return this.pickuplocationField;
        }
        set {
            this.pickuplocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contact-info")]
    public ContactInfoResponseDetailsType contactinfo {
        get {
            return this.contactinfoField;
        }
        set {
            this.contactinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("location-details")]
    public LocationDetailsType locationdetails {
        get {
            return this.locationdetailsField;
        }
        set {
            this.locationdetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("items-characteristics")]
    public ItemsCharacteristicsType itemscharacteristics {
        get {
            return this.itemscharacteristicsField;
        }
        set {
            this.itemscharacteristicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-volume", DataType="normalizedString")]
    public string pickupvolume {
        get {
            return this.pickupvolumeField;
        }
        set {
            this.pickupvolumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-times")]
    public PickupTimesType pickuptimes {
        get {
            return this.pickuptimesField;
        }
        set {
            this.pickuptimesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class LocationDetailsType {
    
    private bool fivetonflagField;
    
    private bool fivetonflagFieldSpecified;
    
    private bool loadingdockflagField;
    
    private bool loadingdockflagFieldSpecified;
    
    private string pickupinstructionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("five-ton-flag")]
    public bool fivetonflag {
        get {
            return this.fivetonflagField;
        }
        set {
            this.fivetonflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fivetonflagSpecified {
        get {
            return this.fivetonflagFieldSpecified;
        }
        set {
            this.fivetonflagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("loading-dock-flag")]
    public bool loadingdockflag {
        get {
            return this.loadingdockflagField;
        }
        set {
            this.loadingdockflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool loadingdockflagSpecified {
        get {
            return this.loadingdockflagFieldSpecified;
        }
        set {
            this.loadingdockflagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-instructions")]
    public string pickupinstructions {
        get {
            return this.pickupinstructionsField;
        }
        set {
            this.pickupinstructionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class ItemsCharacteristicsType {
    
    private bool pwwflagField;
    
    private bool pwwflagFieldSpecified;
    
    private bool priorityflagField;
    
    private bool priorityflagFieldSpecified;
    
    private bool returnsflagField;
    
    private bool returnsflagFieldSpecified;
    
    private bool heavyitemflagField;
    
    private bool heavyitemflagFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pww-flag")]
    public bool pwwflag {
        get {
            return this.pwwflagField;
        }
        set {
            this.pwwflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pwwflagSpecified {
        get {
            return this.pwwflagFieldSpecified;
        }
        set {
            this.pwwflagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("priority-flag")]
    public bool priorityflag {
        get {
            return this.priorityflagField;
        }
        set {
            this.priorityflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priorityflagSpecified {
        get {
            return this.priorityflagFieldSpecified;
        }
        set {
            this.priorityflagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("returns-flag")]
    public bool returnsflag {
        get {
            return this.returnsflagField;
        }
        set {
            this.returnsflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool returnsflagSpecified {
        get {
            return this.returnsflagFieldSpecified;
        }
        set {
            this.returnsflagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("heavy-item-flag")]
    public bool heavyitemflag {
        get {
            return this.heavyitemflagField;
        }
        set {
            this.heavyitemflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool heavyitemflagSpecified {
        get {
            return this.heavyitemflagFieldSpecified;
        }
        set {
            this.heavyitemflagFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class PickupTimesType {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("on-demand-pickup-time", typeof(OnDemandPickupTimeType))]
    [System.Xml.Serialization.XmlElementAttribute("scheduled-pickup-times", typeof(ScheduledPickupTimesType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class OnDemandPickupTimeType {
    
    private System.DateTime dateField;
    
    private string preferredtimeField;
    
    private string closingtimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("preferred-time")]
    public string preferredtime {
        get {
            return this.preferredtimeField;
        }
        set {
            this.preferredtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("closing-time")]
    public string closingtime {
        get {
            return this.closingtimeField;
        }
        set {
            this.closingtimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class ScheduledPickupTimesType {
    
    private PickupTimesPerDayType[] pickuptimesperdayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-times-per-day")]
    public PickupTimesPerDayType[] pickuptimesperday {
        get {
            return this.pickuptimesperdayField;
        }
        set {
            this.pickuptimesperdayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class PickupTimesPerDayType {
    
    private DayOfTheWeekType dayField;
    
    private string preferredtime1Field;
    
    private string preferredtime2Field;
    
    private string closingtimeField;
    
    /// <remarks/>
    public DayOfTheWeekType day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("preferred-time-1")]
    public string preferredtime1 {
        get {
            return this.preferredtime1Field;
        }
        set {
            this.preferredtime1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("preferred-time-2")]
    public string preferredtime2 {
        get {
            return this.preferredtime2Field;
        }
        set {
            this.preferredtime2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("closing-time")]
    public string closingtime {
        get {
            return this.closingtimeField;
        }
        set {
            this.closingtimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public enum DayOfTheWeekType {
    
    /// <remarks/>
    MON,
    
    /// <remarks/>
    TUE,
    
    /// <remarks/>
    WED,
    
    /// <remarks/>
    THU,
    
    /// <remarks/>
    FRI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class SupplierAccountReceiptDetailsType {
    
    private string merchantnameField;
    
    private string merchanturlField;
    
    private string authcodeField;
    
    private System.DateTime authtimestampField;
    
    private string supplieridField;
    
    private decimal chargeamountField;
    
    private string currencyField;
    
    private string transactiontypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-name", DataType="normalizedString")]
    public string merchantname {
        get {
            return this.merchantnameField;
        }
        set {
            this.merchantnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-url", DataType="normalizedString")]
    public string merchanturl {
        get {
            return this.merchanturlField;
        }
        set {
            this.merchanturlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-code", DataType="normalizedString")]
    public string authcode {
        get {
            return this.authcodeField;
        }
        set {
            this.authcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-timestamp")]
    public System.DateTime authtimestamp {
        get {
            return this.authtimestampField;
        }
        set {
            this.authtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("supplier-id", DataType="normalizedString")]
    public string supplierid {
        get {
            return this.supplieridField;
        }
        set {
            this.supplieridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("charge-amount")]
    public decimal chargeamount {
        get {
            return this.chargeamountField;
        }
        set {
            this.chargeamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transaction-type", DataType="normalizedString")]
    public string transactiontype {
        get {
            return this.transactiontypeField;
        }
        set {
            this.transactiontypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="cc-receipt-details-type", Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class ccreceiptdetailstype {
    
    private string merchantnameField;
    
    private string merchanturlField;
    
    private string nameoncardField;
    
    private string authcodeField;
    
    private System.DateTime authtimestampField;
    
    private string cardtypeField;
    
    private decimal chargeamountField;
    
    private string currencyField;
    
    private string transactiontypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-name", DataType="normalizedString")]
    public string merchantname {
        get {
            return this.merchantnameField;
        }
        set {
            this.merchantnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-url", DataType="normalizedString")]
    public string merchanturl {
        get {
            return this.merchanturlField;
        }
        set {
            this.merchanturlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name-on-card", DataType="normalizedString")]
    public string nameoncard {
        get {
            return this.nameoncardField;
        }
        set {
            this.nameoncardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-code", DataType="normalizedString")]
    public string authcode {
        get {
            return this.authcodeField;
        }
        set {
            this.authcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-timestamp")]
    public System.DateTime authtimestamp {
        get {
            return this.authtimestampField;
        }
        set {
            this.authtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("card-type", DataType="normalizedString")]
    public string cardtype {
        get {
            return this.cardtypeField;
        }
        set {
            this.cardtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("charge-amount")]
    public decimal chargeamount {
        get {
            return this.chargeamountField;
        }
        set {
            this.chargeamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transaction-type", DataType="normalizedString")]
    public string transactiontype {
        get {
            return this.transactiontypeField;
        }
        set {
            this.transactiontypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class PickupRequestPriceType {
    
    private decimal pretaxamountField;
    
    private decimal gstamountField;
    
    private bool gstamountFieldSpecified;
    
    private decimal pstamountField;
    
    private bool pstamountFieldSpecified;
    
    private decimal hstamountField;
    
    private bool hstamountFieldSpecified;
    
    private decimal dueamountField;
    
    private ccreceiptdetailstype ccreceiptdetailsField;
    
    private SupplierAccountReceiptDetailsType supplieraccountreceiptdetailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pre-tax-amount")]
    public decimal pretaxamount {
        get {
            return this.pretaxamountField;
        }
        set {
            this.pretaxamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gst-amount")]
    public decimal gstamount {
        get {
            return this.gstamountField;
        }
        set {
            this.gstamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gstamountSpecified {
        get {
            return this.gstamountFieldSpecified;
        }
        set {
            this.gstamountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pst-amount")]
    public decimal pstamount {
        get {
            return this.pstamountField;
        }
        set {
            this.pstamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pstamountSpecified {
        get {
            return this.pstamountFieldSpecified;
        }
        set {
            this.pstamountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("hst-amount")]
    public decimal hstamount {
        get {
            return this.hstamountField;
        }
        set {
            this.hstamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hstamountSpecified {
        get {
            return this.hstamountFieldSpecified;
        }
        set {
            this.hstamountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("due-amount")]
    public decimal dueamount {
        get {
            return this.dueamountField;
        }
        set {
            this.dueamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cc-receipt-details")]
    public ccreceiptdetailstype ccreceiptdetails {
        get {
            return this.ccreceiptdetailsField;
        }
        set {
            this.ccreceiptdetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("supplier-account-receipt-details")]
    public SupplierAccountReceiptDetailsType supplieraccountreceiptdetails {
        get {
            return this.supplieraccountreceiptdetailsField;
        }
        set {
            this.supplieraccountreceiptdetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class ItemsCharacteristicsUpdateDetailsType {
    
    private bool heavyitemflagField;
    
    private bool heavyitemflagFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("heavy-item-flag")]
    public bool heavyitemflag {
        get {
            return this.heavyitemflagField;
        }
        set {
            this.heavyitemflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool heavyitemflagSpecified {
        get {
            return this.heavyitemflagFieldSpecified;
        }
        set {
            this.heavyitemflagFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class PaymentInfoType {
    
    private string contractidField;
    
    private MethodOfPaymentType methodofpaymentField;
    
    private bool methodofpaymentFieldSpecified;
    
    private PreAuthorizedPaymentType preauthorizedpaymentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contract-id")]
    public string contractid {
        get {
            return this.contractidField;
        }
        set {
            this.contractidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("method-of-payment")]
    public MethodOfPaymentType methodofpayment {
        get {
            return this.methodofpaymentField;
        }
        set {
            this.methodofpaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool methodofpaymentSpecified {
        get {
            return this.methodofpaymentFieldSpecified;
        }
        set {
            this.methodofpaymentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pre-authorized-payment")]
    public PreAuthorizedPaymentType preauthorizedpayment {
        get {
            return this.preauthorizedpaymentField;
        }
        set {
            this.preauthorizedpaymentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public enum MethodOfPaymentType {
    
    /// <remarks/>
    CreditCard,
    
    /// <remarks/>
    Account,
    
    /// <remarks/>
    SupplierAccount,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
public partial class ContactInfoType {
    
    private string contactnameField;
    
    private string emailField;
    
    private string contactphoneField;
    
    private string telephoneextField;
    
    private bool receiveemailupdatesflagField;
    
    private bool receiveemailupdatesflagFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contact-name")]
    public string contactname {
        get {
            return this.contactnameField;
        }
        set {
            this.contactnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contact-phone", DataType="normalizedString")]
    public string contactphone {
        get {
            return this.contactphoneField;
        }
        set {
            this.contactphoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("telephone-ext", DataType="normalizedString")]
    public string telephoneext {
        get {
            return this.telephoneextField;
        }
        set {
            this.telephoneextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("receive-email-updates-flag")]
    public bool receiveemailupdatesflag {
        get {
            return this.receiveemailupdatesflagField;
        }
        set {
            this.receiveemailupdatesflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool receiveemailupdatesflagSpecified {
        get {
            return this.receiveemailupdatesflagFieldSpecified;
        }
        set {
            this.receiveemailupdatesflagFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
[System.Xml.Serialization.XmlRootAttribute("pickup-request-update", Namespace="http://www.canadapost.ca/ws/pickuprequest", IsNullable=false)]
public partial class PickupRequestUpdateDetailsType {
    
    private ContactInfoType contactinfoField;
    
    private LocationDetailsType locationdetailsField;
    
    private ItemsCharacteristicsUpdateDetailsType itemscharacteristicsField;
    
    private string pickupvolumeField;
    
    private PickupTimesType pickuptimesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contact-info")]
    public ContactInfoType contactinfo {
        get {
            return this.contactinfoField;
        }
        set {
            this.contactinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("location-details")]
    public LocationDetailsType locationdetails {
        get {
            return this.locationdetailsField;
        }
        set {
            this.locationdetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("items-characteristics")]
    public ItemsCharacteristicsUpdateDetailsType itemscharacteristics {
        get {
            return this.itemscharacteristicsField;
        }
        set {
            this.itemscharacteristicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-volume", DataType="normalizedString")]
    public string pickupvolume {
        get {
            return this.pickupvolumeField;
        }
        set {
            this.pickupvolumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-times")]
    public PickupTimesType pickuptimes {
        get {
            return this.pickuptimesField;
        }
        set {
            this.pickuptimesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
[System.Xml.Serialization.XmlRootAttribute("pickup-request-info", Namespace="http://www.canadapost.ca/ws/pickuprequest", IsNullable=false)]
public partial class PickupRequestInfoType {
    
    private PickupRequestHeaderType pickuprequestheaderField;
    
    private PickupRequestPriceType pickuprequestpriceField;
    
    private LinkType[] linksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-request-header")]
    public PickupRequestHeaderType pickuprequestheader {
        get {
            return this.pickuprequestheaderField;
        }
        set {
            this.pickuprequestheaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-request-price")]
    public PickupRequestPriceType pickuprequestprice {
        get {
            return this.pickuprequestpriceField;
        }
        set {
            this.pickuprequestpriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable=false)]
    public LinkType[] links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
[System.Xml.Serialization.XmlRootAttribute("pickup-request-detailed-info", Namespace="http://www.canadapost.ca/ws/pickuprequest", IsNullable=false)]
public partial class PickupRequestDetailedInfoType {
    
    private PickupRequestHeaderType pickuprequestheaderField;
    
    private PickupRequestResponseDetailsType pickuprequestdetailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-request-header")]
    public PickupRequestHeaderType pickuprequestheader {
        get {
            return this.pickuprequestheaderField;
        }
        set {
            this.pickuprequestheaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-request-details")]
    public PickupRequestResponseDetailsType pickuprequestdetails {
        get {
            return this.pickuprequestdetailsField;
        }
        set {
            this.pickuprequestdetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
[System.Xml.Serialization.XmlRootAttribute("hold-pickups-info", Namespace="http://www.canadapost.ca/ws/pickuprequest", IsNullable=false)]
public partial class HoldPickupsInfoType {
    
    private System.DateTime effectivedateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("effective-date", DataType="date")]
    public System.DateTime effectivedate {
        get {
            return this.effectivedateField;
        }
        set {
            this.effectivedateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
[System.Xml.Serialization.XmlRootAttribute("resume-pickups-info", Namespace="http://www.canadapost.ca/ws/pickuprequest", IsNullable=false)]
public partial class ResumePickupsInfoType {
    
    private System.DateTime effectivedateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("effective-date", DataType="date")]
    public System.DateTime effectivedate {
        get {
            return this.effectivedateField;
        }
        set {
            this.effectivedateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
[System.Xml.Serialization.XmlRootAttribute("pickup-requests", Namespace="http://www.canadapost.ca/ws/pickuprequest", IsNullable=false)]
public partial class PickupRequestsType {
    
    private PickupRequestType[] pickuprequestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-request")]
    public PickupRequestType[] pickuprequest {
        get {
            return this.pickuprequestField;
        }
        set {
            this.pickuprequestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
[System.Xml.Serialization.XmlRootAttribute("pickup-details", Namespace="http://www.canadapost.ca/ws/pickuprequest", IsNullable=false)]
public partial class PickupDetailsType {
    
    private System.DateTime dateField;
    
    private bool dateFieldSpecified;
    
    private string contractidField;
    
    private bool pwwflagField;
    
    private bool pwwflagFieldSpecified;
    
    private bool priorityflagField;
    
    private bool priorityflagFieldSpecified;
    
    private string alternateaddressprovinceField;
    
    private string alternateaddresspostalcodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateSpecified {
        get {
            return this.dateFieldSpecified;
        }
        set {
            this.dateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contract-id")]
    public string contractid {
        get {
            return this.contractidField;
        }
        set {
            this.contractidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pww-flag")]
    public bool pwwflag {
        get {
            return this.pwwflagField;
        }
        set {
            this.pwwflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pwwflagSpecified {
        get {
            return this.pwwflagFieldSpecified;
        }
        set {
            this.pwwflagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("priority-flag")]
    public bool priorityflag {
        get {
            return this.priorityflagField;
        }
        set {
            this.priorityflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priorityflagSpecified {
        get {
            return this.priorityflagFieldSpecified;
        }
        set {
            this.priorityflagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("alternate-address-province", DataType="normalizedString")]
    public string alternateaddressprovince {
        get {
            return this.alternateaddressprovinceField;
        }
        set {
            this.alternateaddressprovinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("alternate-address-postal-code")]
    public string alternateaddresspostalcode {
        get {
            return this.alternateaddresspostalcodeField;
        }
        set {
            this.alternateaddresspostalcodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/pickuprequest")]
[System.Xml.Serialization.XmlRootAttribute("pickup-request-price", Namespace="http://www.canadapost.ca/ws/pickuprequest", IsNullable=false)]
public partial class PickupRequestPriceNoCCType {
    
    private decimal pretaxamountField;
    
    private decimal gstamountField;
    
    private bool gstamountFieldSpecified;
    
    private decimal pstamountField;
    
    private bool pstamountFieldSpecified;
    
    private decimal hstamountField;
    
    private bool hstamountFieldSpecified;
    
    private decimal dueamountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pre-tax-amount")]
    public decimal pretaxamount {
        get {
            return this.pretaxamountField;
        }
        set {
            this.pretaxamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gst-amount")]
    public decimal gstamount {
        get {
            return this.gstamountField;
        }
        set {
            this.gstamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gstamountSpecified {
        get {
            return this.gstamountFieldSpecified;
        }
        set {
            this.gstamountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pst-amount")]
    public decimal pstamount {
        get {
            return this.pstamountField;
        }
        set {
            this.pstamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pstamountSpecified {
        get {
            return this.pstamountFieldSpecified;
        }
        set {
            this.pstamountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("hst-amount")]
    public decimal hstamount {
        get {
            return this.hstamountField;
        }
        set {
            this.hstamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hstamountSpecified {
        get {
            return this.hstamountFieldSpecified;
        }
        set {
            this.hstamountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("due-amount")]
    public decimal dueamount {
        get {
            return this.dueamountField;
        }
        set {
            this.dueamountField = value;
        }
    }
}
