//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.canadapost.ca/ws/shipment-v8")]
public partial class PrintPreferencesType
{

    private PrintPreferencesTypeOutputformat outputformatField;

    private bool outputformatFieldSpecified;

    private PrintPreferencesTypeEncoding encodingField;

    private bool encodingFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("output-format")]
    public PrintPreferencesTypeOutputformat outputformat
    {
        get
        {
            return this.outputformatField;
        }
        set
        {
            this.outputformatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool outputformatSpecified
    {
        get
        {
            return this.outputformatFieldSpecified;
        }
        set
        {
            this.outputformatFieldSpecified = value;
        }
    }

    /// <remarks/>
    public PrintPreferencesTypeEncoding encoding
    {
        get
        {
            return this.encodingField;
        }
        set
        {
            this.encodingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool encodingSpecified
    {
        get
        {
            return this.encodingFieldSpecified;
        }
        set
        {
            this.encodingFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.canadapost.ca/ws/shipment-v8")]
public enum PrintPreferencesTypeOutputformat
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8.5x11")]
    Item85x11,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4x6")]
    Item4x6,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.canadapost.ca/ws/shipment-v8")]
public enum PrintPreferencesTypeEncoding
{

    /// <remarks/>
    PDF,

    /// <remarks/>
    ZPL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/openreturn-v2")]
public partial class OpenReturnPrintPreferencesType
{
    
    private OpenReturnPrintPreferencesTypeOutputformat outputformatField;
    
    private bool outputformatFieldSpecified;
    
    private string customerinputtypeField;
    
    private OpenReturnPrintPreferencesTypeEncoding encodingField;
    
    private bool encodingFieldSpecified;
    
    private bool showpackinginstructionsField;
    
    private bool showpackinginstructionsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("output-format")]
    public OpenReturnPrintPreferencesTypeOutputformat outputformat {
        get {
            return this.outputformatField;
        }
        set {
            this.outputformatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool outputformatSpecified {
        get {
            return this.outputformatFieldSpecified;
        }
        set {
            this.outputformatFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-input-type", DataType="token")]
    public string customerinputtype {
        get {
            return this.customerinputtypeField;
        }
        set {
            this.customerinputtypeField = value;
        }
    }
    
    /// <remarks/>
    public OpenReturnPrintPreferencesTypeEncoding encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool encodingSpecified {
        get {
            return this.encodingFieldSpecified;
        }
        set {
            this.encodingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("show-packing-instructions")]
    public bool showpackinginstructions {
        get {
            return this.showpackinginstructionsField;
        }
        set {
            this.showpackinginstructionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool showpackinginstructionsSpecified {
        get {
            return this.showpackinginstructionsFieldSpecified;
        }
        set {
            this.showpackinginstructionsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/openreturn-v2")]
public enum OpenReturnPrintPreferencesTypeOutputformat
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8.5x11")]
    Item85x11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4x6")]
    Item4x6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3x5")]
    Item3x5,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/openreturn-v2")]
public enum OpenReturnPrintPreferencesTypeEncoding
{
    /// <remarks/>
    PDF,
    
    /// <remarks/>
    ZPL,
}
