//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/serviceinfo-v2")]
[System.Xml.Serialization.XmlRootAttribute("info-messages", Namespace="http://www.canadapost.ca/ws/serviceinfo-v2", IsNullable=false)]
public partial class InfoMessagesType {
    
    private InfoMessageType[] infomessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("info-message")]
    public InfoMessageType[] infomessage {
        get {
            return this.infomessageField;
        }
        set {
            this.infomessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/serviceinfo-v2")]
[System.Xml.Serialization.XmlRootAttribute("info-message", Namespace="http://www.canadapost.ca/ws/serviceinfo-v2", IsNullable=false)]
public partial class InfoMessageType {
    
    private MessageType messagetypeField;
    
    private string messagetextField;
    
    private System.DateTime fromdatetimeField;
    
    private System.DateTime todatetimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("message-type")]
    public MessageType messagetype {
        get {
            return this.messagetypeField;
        }
        set {
            this.messagetypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("message-text", DataType="token")]
    public string messagetext {
        get {
            return this.messagetextField;
        }
        set {
            this.messagetextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("from-datetime")]
    public System.DateTime fromdatetime {
        get {
            return this.fromdatetimeField;
        }
        set {
            this.fromdatetimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("to-datetime")]
    public System.DateTime todatetime {
        get {
            return this.todatetimeField;
        }
        set {
            this.todatetimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/serviceinfo-v2")]
public enum MessageType {
    
    /// <remarks/>
    SO,
}
