//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class GroupType {
    
    private string groupidField;
    
    private LinkType linkField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("group-id", DataType="normalizedString")]
    public string groupid {
        get {
            return this.groupidField;
        }
        set {
            this.groupidField = value;
        }
    }
    
    /// <remarks/>
    public LinkType link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class ServiceStandardType {
    
    private bool amdeliveryField;
    
    private bool guaranteeddeliveryField;
    
    private string expectedtransmittimeField;
    
    private System.DateTime expecteddeliverydateField;
    
    private bool expecteddeliverydateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("am-delivery")]
    public bool amdelivery {
        get {
            return this.amdeliveryField;
        }
        set {
            this.amdeliveryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("guaranteed-delivery")]
    public bool guaranteeddelivery {
        get {
            return this.guaranteeddeliveryField;
        }
        set {
            this.guaranteeddeliveryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expected-transmit-time", DataType="integer")]
    public string expectedtransmittime {
        get {
            return this.expectedtransmittimeField;
        }
        set {
            this.expectedtransmittimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expected-delivery-date", DataType="date")]
    public System.DateTime expecteddeliverydate {
        get {
            return this.expecteddeliverydateField;
        }
        set {
            this.expecteddeliverydateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expecteddeliverydateSpecified {
        get {
            return this.expecteddeliverydateFieldSpecified;
        }
        set {
            this.expecteddeliverydateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class AdjustmentType {
    
    private string adjustmentcodeField;
    
    private decimal adjustmentamountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adjustment-code", DataType="normalizedString")]
    public string adjustmentcode {
        get {
            return this.adjustmentcodeField;
        }
        set {
            this.adjustmentcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adjustment-amount")]
    public decimal adjustmentamount {
        get {
            return this.adjustmentamountField;
        }
        set {
            this.adjustmentamountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class PricedOptionType {
    
    private string optioncodeField;
    
    private decimal optionpriceField;
    
    private bool optionpriceFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-code", DataType="normalizedString")]
    public string optioncode {
        get {
            return this.optioncodeField;
        }
        set {
            this.optioncodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-price")]
    public decimal optionprice {
        get {
            return this.optionpriceField;
        }
        set {
            this.optionpriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool optionpriceSpecified {
        get {
            return this.optionpriceFieldSpecified;
        }
        set {
            this.optionpriceFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class ReturnRecipientType {
    
    private string nameField;
    
    private string companyField;
    
    private DomesticAddressDetailsType addressdetailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("address-details")]
    public DomesticAddressDetailsType addressdetails {
        get {
            return this.addressdetailsField;
        }
        set {
            this.addressdetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class ReturnSpecType {
    
    private string servicecodeField;
    
    private ReturnRecipientType returnrecipientField;
    
    private string returnnotificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-code", DataType="normalizedString")]
    public string servicecode {
        get {
            return this.servicecodeField;
        }
        set {
            this.servicecodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("return-recipient")]
    public ReturnRecipientType returnrecipient {
        get {
            return this.returnrecipientField;
        }
        set {
            this.returnrecipientField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("return-notification", DataType="normalizedString")]
    public string returnnotification {
        get {
            return this.returnnotificationField;
        }
        set {
            this.returnnotificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class SkuType {
    
    private string customsnumberofunitsField;
    
    private string customsdescriptionField;
    
    private string skuField;
    
    private string hstariffcodeField;
    
    private decimal unitweightField;
    
    private decimal customsvalueperunitField;
    
    private string customsunitofmeasureField;
    
    private string countryoforiginField;
    
    private string provinceoforiginField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customs-number-of-units", DataType="positiveInteger")]
    public string customsnumberofunits {
        get {
            return this.customsnumberofunitsField;
        }
        set {
            this.customsnumberofunitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customs-description", DataType="normalizedString")]
    public string customsdescription {
        get {
            return this.customsdescriptionField;
        }
        set {
            this.customsdescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string sku {
        get {
            return this.skuField;
        }
        set {
            this.skuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("hs-tariff-code")]
    public string hstariffcode {
        get {
            return this.hstariffcodeField;
        }
        set {
            this.hstariffcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("unit-weight")]
    public decimal unitweight {
        get {
            return this.unitweightField;
        }
        set {
            this.unitweightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customs-value-per-unit")]
    public decimal customsvalueperunit {
        get {
            return this.customsvalueperunitField;
        }
        set {
            this.customsvalueperunitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customs-unit-of-measure", DataType="normalizedString")]
    public string customsunitofmeasure {
        get {
            return this.customsunitofmeasureField;
        }
        set {
            this.customsunitofmeasureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("country-of-origin")]
    public string countryoforigin {
        get {
            return this.countryoforiginField;
        }
        set {
            this.countryoforiginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("province-of-origin", DataType="normalizedString")]
    public string provinceoforigin {
        get {
            return this.provinceoforiginField;
        }
        set {
            this.provinceoforiginField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class CustomsType {
    
    private string currencyField;
    
    private decimal conversionfromcadField;
    
    private bool conversionfromcadFieldSpecified;
    
    private string reasonforexportField;
    
    private string otherreasonField;
    
    private NonContractSkuType[] skulistField;
    
    private decimal dutiesandtaxesprepaidField;
    
    private bool dutiesandtaxesprepaidFieldSpecified;
    
    private string certificatenumberField;
    
    private string licencenumberField;
    
    private string invoicenumberField;
    
    private string iossidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("conversion-from-cad")]
    public decimal conversionfromcad {
        get {
            return this.conversionfromcadField;
        }
        set {
            this.conversionfromcadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conversionfromcadSpecified {
        get {
            return this.conversionfromcadFieldSpecified;
        }
        set {
            this.conversionfromcadFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("reason-for-export", DataType="normalizedString")]
    public string reasonforexport {
        get {
            return this.reasonforexportField;
        }
        set {
            this.reasonforexportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("other-reason", DataType="normalizedString")]
    public string otherreason {
        get {
            return this.otherreasonField;
        }
        set {
            this.otherreasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("sku-list")]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public NonContractSkuType[] skulist {
        get {
            return this.skulistField;
        }
        set {
            this.skulistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("duties-and-taxes-prepaid")]
    public decimal dutiesandtaxesprepaid {
        get {
            return this.dutiesandtaxesprepaidField;
        }
        set {
            this.dutiesandtaxesprepaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dutiesandtaxesprepaidSpecified {
        get {
            return this.dutiesandtaxesprepaidFieldSpecified;
        }
        set {
            this.dutiesandtaxesprepaidFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("certificate-number", DataType="normalizedString")]
    public string certificatenumber {
        get {
            return this.certificatenumberField;
        }
        set {
            this.certificatenumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("licence-number", DataType="normalizedString")]
    public string licencenumber {
        get {
            return this.licencenumberField;
        }
        set {
            this.licencenumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("invoice-number", DataType="normalizedString")]
    public string invoicenumber {
        get {
            return this.invoicenumberField;
        }
        set {
            this.invoicenumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ioss-id", DataType="normalizedString")]
    public string iossid {
        get {
            return this.iossidField;
        }
        set {
            this.iossidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class ReferencesType {
    
    private string costcentreField;
    
    private string customerref1Field;
    
    private string customerref2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cost-centre", DataType="normalizedString")]
    public string costcentre {
        get {
            return this.costcentreField;
        }
        set {
            this.costcentreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-ref-1", DataType="normalizedString")]
    public string customerref1 {
        get {
            return this.customerref1Field;
        }
        set {
            this.customerref1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-ref-2", DataType="normalizedString")]
    public string customerref2 {
        get {
            return this.customerref2Field;
        }
        set {
            this.customerref2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class PreferencesType {
    
    private bool showpackinginstructionsField;
    
    private bool showpostagerateField;
    
    private bool showpostagerateFieldSpecified;
    
    private bool showinsuredvalueField;
    
    private bool showinsuredvalueFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("show-packing-instructions")]
    public bool showpackinginstructions {
        get {
            return this.showpackinginstructionsField;
        }
        set {
            this.showpackinginstructionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("show-postage-rate")]
    public bool showpostagerate {
        get {
            return this.showpostagerateField;
        }
        set {
            this.showpostagerateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool showpostagerateSpecified {
        get {
            return this.showpostagerateFieldSpecified;
        }
        set {
            this.showpostagerateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("show-insured-value")]
    public bool showinsuredvalue {
        get {
            return this.showinsuredvalueField;
        }
        set {
            this.showinsuredvalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool showinsuredvalueSpecified {
        get {
            return this.showinsuredvalueFieldSpecified;
        }
        set {
            this.showinsuredvalueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class NotificationType {
    
    private string emailField;
    
    private bool onshipmentField;
    
    private bool onexceptionField;
    
    private bool ondeliveryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("on-shipment")]
    public bool onshipment {
        get {
            return this.onshipmentField;
        }
        set {
            this.onshipmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("on-exception")]
    public bool onexception {
        get {
            return this.onexceptionField;
        }
        set {
            this.onexceptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("on-delivery")]
    public bool ondelivery {
        get {
            return this.ondeliveryField;
        }
        set {
            this.ondeliveryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class OptionType {
    
    private string optioncodeField;
    
    private decimal optionamountField;
    
    private bool optionamountFieldSpecified;
    
    private bool optionqualifier1Field;
    
    private bool optionqualifier1FieldSpecified;
    
    private string optionqualifier2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-code", DataType="normalizedString")]
    public string optioncode {
        get {
            return this.optioncodeField;
        }
        set {
            this.optioncodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-amount")]
    public decimal optionamount {
        get {
            return this.optionamountField;
        }
        set {
            this.optionamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool optionamountSpecified {
        get {
            return this.optionamountFieldSpecified;
        }
        set {
            this.optionamountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-qualifier-1")]
    public bool optionqualifier1 {
        get {
            return this.optionqualifier1Field;
        }
        set {
            this.optionqualifier1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool optionqualifier1Specified {
        get {
            return this.optionqualifier1FieldSpecified;
        }
        set {
            this.optionqualifier1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-qualifier-2", DataType="normalizedString")]
    public string optionqualifier2 {
        get {
            return this.optionqualifier2Field;
        }
        set {
            this.optionqualifier2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class DestinationType {
    
    private string nameField;
    
    private string companyField;
    
    private string additionaladdressinfoField;
    
    private string clientvoicenumberField;
    
    private DestinationAddressDetailsType addressdetailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("additional-address-info", DataType="normalizedString")]
    public string additionaladdressinfo {
        get {
            return this.additionaladdressinfoField;
        }
        set {
            this.additionaladdressinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-voice-number", DataType="normalizedString")]
    public string clientvoicenumber {
        get {
            return this.clientvoicenumberField;
        }
        set {
            this.clientvoicenumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("address-details")]
    public DestinationAddressDetailsType addressdetails {
        get {
            return this.addressdetailsField;
        }
        set {
            this.addressdetailsField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class SenderType {
    
    private string nameField;
    
    private string companyField;
    
    private string contactphoneField;
    
    private AddressDetailsType addressdetailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contact-phone", DataType="normalizedString")]
    public string contactphone {
        get {
            return this.contactphoneField;
        }
        set {
            this.contactphoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("address-details")]
    public AddressDetailsType addressdetails {
        get {
            return this.addressdetailsField;
        }
        set {
            this.addressdetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class DeliverySpecType {
    
    private string servicecodeField;
    
    private SenderType senderField;
    
    private DestinationType destinationField;
    
    private OptionType[] optionsField;
    
    private ParcelCharacteristicsType parcelcharacteristicsField;
    
    private NotificationType notificationField;
    
    private PrintPreferencesType printpreferencesField;
    
    private PreferencesType preferencesField;
    
    private ReferencesType referencesField;
    
    private NonContractCustomsType customsField;
    
    private SettlementInfoType settlementinfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-code", DataType="normalizedString")]
    public string servicecode {
        get {
            return this.servicecodeField;
        }
        set {
            this.servicecodeField = value;
        }
    }
    
    /// <remarks/>
    public SenderType sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    public DestinationType destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("option", IsNullable=false)]
    public OptionType[] options {
        get {
            return this.optionsField;
        }
        set {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parcel-characteristics")]
    public ParcelCharacteristicsType parcelcharacteristics {
        get {
            return this.parcelcharacteristicsField;
        }
        set {
            this.parcelcharacteristicsField = value;
        }
    }
    
    /// <remarks/>
    public NotificationType notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("print-preferences")]
    public PrintPreferencesType printpreferences {
        get {
            return this.printpreferencesField;
        }
        set {
            this.printpreferencesField = value;
        }
    }
    
    /// <remarks/>
    public PreferencesType preferences {
        get {
            return this.preferencesField;
        }
        set {
            this.preferencesField = value;
        }
    }
    
    /// <remarks/>
    public ReferencesType references {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    public NonContractCustomsType customs {
        get {
            return this.customsField;
        }
        set {
            this.customsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("settlement-info")]
    public SettlementInfoType settlementinfo {
        get {
            return this.settlementinfoField;
        }
        set {
            this.settlementinfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
[System.Xml.Serialization.XmlRootAttribute("shipment", Namespace="http://www.canadapost.ca/ws/shipment-v8", IsNullable=false)]
public partial class ShipmentType {
    
    private string customerrequestidField;
    
    private object itemField;
    
    private bool quickshiplabelrequestedField;
    
    private bool quickshiplabelrequestedFieldSpecified;
    
    private bool cpcpickupindicatorField;
    
    private bool cpcpickupindicatorFieldSpecified;
    
    private string requestedshippingpointField;
    
    private string shippingpointidField;
    
    private System.DateTime expectedmailingdateField;
    
    private bool expectedmailingdateFieldSpecified;
    
    private bool providepricinginfoField;
    
    private bool providepricinginfoFieldSpecified;
    
    private bool providereceiptinfoField;
    
    private bool providereceiptinfoFieldSpecified;
    
    private DeliverySpecType deliveryspecField;
    
    private ReturnSpecType returnspecField;
    
    private PreAuthorizedPaymentType preauthorizedpaymentField;
    
    public ShipmentType() {
        this.cpcpickupindicatorField = true;
        this.providepricinginfoField = true;
        this.providereceiptinfoField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-request-id", DataType="normalizedString")]
    public string customerrequestid {
        get {
            return this.customerrequestidField;
        }
        set {
            this.customerrequestidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("group-id", typeof(string), DataType="normalizedString")]
    [System.Xml.Serialization.XmlElementAttribute("transmit-shipment", typeof(bool))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quickship-label-requested")]
    public bool quickshiplabelrequested {
        get {
            return this.quickshiplabelrequestedField;
        }
        set {
            this.quickshiplabelrequestedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool quickshiplabelrequestedSpecified {
        get {
            return this.quickshiplabelrequestedFieldSpecified;
        }
        set {
            this.quickshiplabelrequestedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cpc-pickup-indicator")]
    public bool cpcpickupindicator {
        get {
            return this.cpcpickupindicatorField;
        }
        set {
            this.cpcpickupindicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cpcpickupindicatorSpecified {
        get {
            return this.cpcpickupindicatorFieldSpecified;
        }
        set {
            this.cpcpickupindicatorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("requested-shipping-point")]
    public string requestedshippingpoint {
        get {
            return this.requestedshippingpointField;
        }
        set {
            this.requestedshippingpointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-point-id", DataType="normalizedString")]
    public string shippingpointid {
        get {
            return this.shippingpointidField;
        }
        set {
            this.shippingpointidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expected-mailing-date", DataType="date")]
    public System.DateTime expectedmailingdate {
        get {
            return this.expectedmailingdateField;
        }
        set {
            this.expectedmailingdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expectedmailingdateSpecified {
        get {
            return this.expectedmailingdateFieldSpecified;
        }
        set {
            this.expectedmailingdateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("provide-pricing-info")]
    public bool providepricinginfo {
        get {
            return this.providepricinginfoField;
        }
        set {
            this.providepricinginfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool providepricinginfoSpecified {
        get {
            return this.providepricinginfoFieldSpecified;
        }
        set {
            this.providepricinginfoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("provide-receipt-info")]
    public bool providereceiptinfo {
        get {
            return this.providereceiptinfoField;
        }
        set {
            this.providereceiptinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool providereceiptinfoSpecified {
        get {
            return this.providereceiptinfoFieldSpecified;
        }
        set {
            this.providereceiptinfoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("delivery-spec")]
    public DeliverySpecType deliveryspec {
        get {
            return this.deliveryspecField;
        }
        set {
            this.deliveryspecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("return-spec")]
    public ReturnSpecType returnspec {
        get {
            return this.returnspecField;
        }
        set {
            this.returnspecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pre-authorized-payment")]
    public PreAuthorizedPaymentType preauthorizedpayment {
        get {
            return this.preauthorizedpaymentField;
        }
        set {
            this.preauthorizedpaymentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
[System.Xml.Serialization.XmlRootAttribute("shipment-info", Namespace="http://www.canadapost.ca/ws/shipment-v8", IsNullable=false)]
public partial class ShipmentInfoType {
    
    private string customerrequestidField;
    
    private string shipmentidField;
    
    private string shipmentstatusField;
    
    private string trackingpinField;
    
    private string returntrackingpinField;
    
    private string ponumberField;
    
    private ShipmentPriceType shipmentpriceField;
    
    private ShipmentReceiptType shipmentreceiptField;
    
    private LinkType[] linksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-request-id", DataType="normalizedString")]
    public string customerrequestid {
        get {
            return this.customerrequestidField;
        }
        set {
            this.customerrequestidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipment-id", DataType="normalizedString")]
    public string shipmentid {
        get {
            return this.shipmentidField;
        }
        set {
            this.shipmentidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipment-status", DataType="normalizedString")]
    public string shipmentstatus {
        get {
            return this.shipmentstatusField;
        }
        set {
            this.shipmentstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tracking-pin", DataType="normalizedString")]
    public string trackingpin {
        get {
            return this.trackingpinField;
        }
        set {
            this.trackingpinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("return-tracking-pin", DataType="normalizedString")]
    public string returntrackingpin {
        get {
            return this.returntrackingpinField;
        }
        set {
            this.returntrackingpinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-number")]
    public string ponumber {
        get {
            return this.ponumberField;
        }
        set {
            this.ponumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipment-price")]
    public ShipmentPriceType shipmentprice {
        get {
            return this.shipmentpriceField;
        }
        set {
            this.shipmentpriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipment-receipt")]
    public ShipmentReceiptType shipmentreceipt {
        get {
            return this.shipmentreceiptField;
        }
        set {
            this.shipmentreceiptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable=false)]
    public LinkType[] links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
[System.Xml.Serialization.XmlRootAttribute("shipment-price", Namespace="http://www.canadapost.ca/ws/shipment-v8", IsNullable=false)]
public partial class ShipmentPriceType {
    
    private string servicecodeField;
    
    private decimal baseamountField;
    
    private PricedOptionType[] pricedoptionsField;
    
    private AdjustmentType[] adjustmentsField;
    
    private decimal pretaxamountField;
    
    private decimal gstamountField;
    
    private decimal pstamountField;
    
    private decimal hstamountField;
    
    private decimal dueamountField;
    
    private ServiceStandardType servicestandardField;
    
    private decimal ratedweightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-code", DataType="normalizedString")]
    public string servicecode {
        get {
            return this.servicecodeField;
        }
        set {
            this.servicecodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("base-amount")]
    public decimal baseamount {
        get {
            return this.baseamountField;
        }
        set {
            this.baseamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("priced-options")]
    [System.Xml.Serialization.XmlArrayItemAttribute("priced-option", IsNullable=false)]
    public PricedOptionType[] pricedoptions {
        get {
            return this.pricedoptionsField;
        }
        set {
            this.pricedoptionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("adjustment", IsNullable=false)]
    public AdjustmentType[] adjustments {
        get {
            return this.adjustmentsField;
        }
        set {
            this.adjustmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pre-tax-amount")]
    public decimal pretaxamount {
        get {
            return this.pretaxamountField;
        }
        set {
            this.pretaxamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gst-amount")]
    public decimal gstamount {
        get {
            return this.gstamountField;
        }
        set {
            this.gstamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pst-amount")]
    public decimal pstamount {
        get {
            return this.pstamountField;
        }
        set {
            this.pstamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("hst-amount")]
    public decimal hstamount {
        get {
            return this.hstamountField;
        }
        set {
            this.hstamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("due-amount")]
    public decimal dueamount {
        get {
            return this.dueamountField;
        }
        set {
            this.dueamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-standard")]
    public ServiceStandardType servicestandard {
        get {
            return this.servicestandardField;
        }
        set {
            this.servicestandardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rated-weight")]
    public decimal ratedweight {
        get {
            return this.ratedweightField;
        }
        set {
            this.ratedweightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
[System.Xml.Serialization.XmlRootAttribute("shipment-receipt", Namespace="http://www.canadapost.ca/ws/shipment-v8", IsNullable=false)]
public partial class ShipmentReceiptType {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cc-receipt-details", typeof(ShipmentReceiptTypeCcreceiptdetails))]
    [System.Xml.Serialization.XmlElementAttribute("supplier-account-receipt-details", typeof(ShipmentReceiptTypeSupplieraccountreceiptdetails))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class ShipmentReceiptTypeCcreceiptdetails {
    
    private string merchantnameField;
    
    private string merchanturlField;
    
    private string nameoncardField;
    
    private string authcodeField;
    
    private System.DateTime authtimestampField;
    
    private CcType cardtypeField;
    
    private decimal chargeamountField;
    
    private string currencyField;
    
    private string transactiontypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-name", DataType="normalizedString")]
    public string merchantname {
        get {
            return this.merchantnameField;
        }
        set {
            this.merchantnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-url", DataType="normalizedString")]
    public string merchanturl {
        get {
            return this.merchanturlField;
        }
        set {
            this.merchanturlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name-on-card", DataType="normalizedString")]
    public string nameoncard {
        get {
            return this.nameoncardField;
        }
        set {
            this.nameoncardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-code", DataType="normalizedString")]
    public string authcode {
        get {
            return this.authcodeField;
        }
        set {
            this.authcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-timestamp")]
    public System.DateTime authtimestamp {
        get {
            return this.authtimestampField;
        }
        set {
            this.authtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("card-type")]
    public CcType cardtype {
        get {
            return this.cardtypeField;
        }
        set {
            this.cardtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("charge-amount")]
    public decimal chargeamount {
        get {
            return this.chargeamountField;
        }
        set {
            this.chargeamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transaction-type", DataType="normalizedString")]
    public string transactiontype {
        get {
            return this.transactiontypeField;
        }
        set {
            this.transactiontypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class ShipmentReceiptTypeSupplieraccountreceiptdetails {
    
    private string merchantnameField;
    
    private string merchanturlField;
    
    private string authcodeField;
    
    private System.DateTime authtimestampField;
    
    private string supplieridField;
    
    private decimal chargeamountField;
    
    private string currencyField;
    
    private string transactiontypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-name", DataType="normalizedString")]
    public string merchantname {
        get {
            return this.merchantnameField;
        }
        set {
            this.merchantnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-url", DataType="normalizedString")]
    public string merchanturl {
        get {
            return this.merchanturlField;
        }
        set {
            this.merchanturlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-code", DataType="normalizedString")]
    public string authcode {
        get {
            return this.authcodeField;
        }
        set {
            this.authcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-timestamp")]
    public System.DateTime authtimestamp {
        get {
            return this.authtimestampField;
        }
        set {
            this.authtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("supplier-id", DataType="normalizedString")]
    public string supplierid {
        get {
            return this.supplieridField;
        }
        set {
            this.supplieridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("charge-amount")]
    public decimal chargeamount {
        get {
            return this.chargeamountField;
        }
        set {
            this.chargeamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transaction-type", DataType="normalizedString")]
    public string transactiontype {
        get {
            return this.transactiontypeField;
        }
        set {
            this.transactiontypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
[System.Xml.Serialization.XmlRootAttribute("shipment-details", Namespace="http://www.canadapost.ca/ws/shipment-v8", IsNullable=false)]
public partial class ShipmentDetailsType {
    
    private string customerrequestidField;
    
    private string shipmentstatusField;
    
    private string finalshippingpointField;
    
    private string trackingpinField;
    
    private string ponumberField;
    
    private string shippingpointidField;
    
    private bool cpcpickupindicatorField;
    
    private bool cpcpickupindicatorFieldSpecified;
    
    private ShipmentDetailsTypeShipmentdetail shipmentdetailField;
    
    public ShipmentDetailsType() {
        this.cpcpickupindicatorField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-request-id", DataType="normalizedString")]
    public string customerrequestid {
        get {
            return this.customerrequestidField;
        }
        set {
            this.customerrequestidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipment-status", DataType="normalizedString")]
    public string shipmentstatus {
        get {
            return this.shipmentstatusField;
        }
        set {
            this.shipmentstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("final-shipping-point")]
    public string finalshippingpoint {
        get {
            return this.finalshippingpointField;
        }
        set {
            this.finalshippingpointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tracking-pin", DataType="normalizedString")]
    public string trackingpin {
        get {
            return this.trackingpinField;
        }
        set {
            this.trackingpinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-number")]
    public string ponumber {
        get {
            return this.ponumberField;
        }
        set {
            this.ponumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-point-id", DataType="normalizedString")]
    public string shippingpointid {
        get {
            return this.shippingpointidField;
        }
        set {
            this.shippingpointidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cpc-pickup-indicator")]
    public bool cpcpickupindicator {
        get {
            return this.cpcpickupindicatorField;
        }
        set {
            this.cpcpickupindicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cpcpickupindicatorSpecified {
        get {
            return this.cpcpickupindicatorFieldSpecified;
        }
        set {
            this.cpcpickupindicatorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipment-detail")]
    public ShipmentDetailsTypeShipmentdetail shipmentdetail {
        get {
            return this.shipmentdetailField;
        }
        set {
            this.shipmentdetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class ShipmentDetailsTypeShipmentdetail {
    
    private object itemField;
    
    private bool quickshiplabelrequestedField;
    
    private bool quickshiplabelrequestedFieldSpecified;
    
    private System.DateTime expectedmailingdateField;
    
    private bool expectedmailingdateFieldSpecified;
    
    private ShipmentDetailsTypeShipmentdetailDeliveryspec deliveryspecField;
    
    private ReturnSpecType returnspecField;
    
    private ShipmentRefundRequestInfoType refundrequestinfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("group-id", typeof(string), DataType="normalizedString")]
    [System.Xml.Serialization.XmlElementAttribute("transmit-shipment", typeof(bool))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quickship-label-requested")]
    public bool quickshiplabelrequested {
        get {
            return this.quickshiplabelrequestedField;
        }
        set {
            this.quickshiplabelrequestedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool quickshiplabelrequestedSpecified {
        get {
            return this.quickshiplabelrequestedFieldSpecified;
        }
        set {
            this.quickshiplabelrequestedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expected-mailing-date", DataType="date")]
    public System.DateTime expectedmailingdate {
        get {
            return this.expectedmailingdateField;
        }
        set {
            this.expectedmailingdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expectedmailingdateSpecified {
        get {
            return this.expectedmailingdateFieldSpecified;
        }
        set {
            this.expectedmailingdateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("delivery-spec")]
    public ShipmentDetailsTypeShipmentdetailDeliveryspec deliveryspec {
        get {
            return this.deliveryspecField;
        }
        set {
            this.deliveryspecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("return-spec")]
    public ReturnSpecType returnspec {
        get {
            return this.returnspecField;
        }
        set {
            this.returnspecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("refund-request-info")]
    public ShipmentRefundRequestInfoType refundrequestinfo {
        get {
            return this.refundrequestinfoField;
        }
        set {
            this.refundrequestinfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class ShipmentDetailsTypeShipmentdetailDeliveryspec {
    
    private string servicecodeField;
    
    private SenderType senderField;
    
    private DestinationType destinationField;
    
    private RecipientAddressType recipientField;
    
    private OptionType[] optionsField;
    
    private ParcelCharacteristicsType parcelcharacteristicsField;
    
    private NotificationType notificationField;
    
    private PrintPreferencesType printpreferencesField;
    
    private PreferencesType preferencesField;
    
    private ReferencesType referencesField;
    
    private NonContractCustomsType customsField;
    
    private SettlementInfoType settlementinfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-code", DataType="normalizedString")]
    public string servicecode {
        get {
            return this.servicecodeField;
        }
        set {
            this.servicecodeField = value;
        }
    }
    
    /// <remarks/>
    public SenderType sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    public DestinationType destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    public RecipientAddressType recipient {
        get {
            return this.recipientField;
        }
        set {
            this.recipientField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("option", IsNullable=false)]
    public OptionType[] options {
        get {
            return this.optionsField;
        }
        set {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parcel-characteristics")]
    public ParcelCharacteristicsType parcelcharacteristics {
        get {
            return this.parcelcharacteristicsField;
        }
        set {
            this.parcelcharacteristicsField = value;
        }
    }
    
    /// <remarks/>
    public NotificationType notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("print-preferences")]
    public PrintPreferencesType printpreferences {
        get {
            return this.printpreferencesField;
        }
        set {
            this.printpreferencesField = value;
        }
    }
    
    /// <remarks/>
    public PreferencesType preferences {
        get {
            return this.preferencesField;
        }
        set {
            this.preferencesField = value;
        }
    }
    
    /// <remarks/>
    public ReferencesType references {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    public NonContractCustomsType customs {
        get {
            return this.customsField;
        }
        set {
            this.customsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("settlement-info")]
    public SettlementInfoType settlementinfo {
        get {
            return this.settlementinfoField;
        }
        set {
            this.settlementinfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
[System.Xml.Serialization.XmlRootAttribute("shipment-refund-request-info", Namespace="http://www.canadapost.ca/ws/shipment-v8", IsNullable=false)]
public partial class ShipmentRefundRequestInfoType {
    
    private System.DateTime serviceticketdateField;
    
    private string serviceticketidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-ticket-date", DataType="date")]
    public System.DateTime serviceticketdate {
        get {
            return this.serviceticketdateField;
        }
        set {
            this.serviceticketdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-ticket-id", DataType="normalizedString")]
    public string serviceticketid {
        get {
            return this.serviceticketidField;
        }
        set {
            this.serviceticketidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
[System.Xml.Serialization.XmlRootAttribute("shipments", Namespace="http://www.canadapost.ca/ws/shipment-v8", IsNullable=false)]
public partial class ShipmentsType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link", typeof(LinkType))]
    [System.Xml.Serialization.XmlElementAttribute("shipment-info", typeof(ShipmentInfoType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
[System.Xml.Serialization.XmlRootAttribute("shipment-cc-receipt", Namespace="http://www.canadapost.ca/ws/shipment-v8", IsNullable=false)]
public partial class ShipmentCCReceiptType {
    
    private ShipmentCCReceiptTypeCcreceiptdetails ccreceiptdetailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cc-receipt-details")]
    public ShipmentCCReceiptTypeCcreceiptdetails ccreceiptdetails {
        get {
            return this.ccreceiptdetailsField;
        }
        set {
            this.ccreceiptdetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/shipment-v8")]
public partial class ShipmentCCReceiptTypeCcreceiptdetails {
    
    private string merchantnameField;
    
    private string merchanturlField;
    
    private string nameoncardField;
    
    private string authcodeField;
    
    private System.DateTime authtimestampField;
    
    private CcType cardtypeField;
    
    private decimal chargeamountField;
    
    private string currencyField;
    
    private string transactiontypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-name", DataType="normalizedString")]
    public string merchantname {
        get {
            return this.merchantnameField;
        }
        set {
            this.merchantnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-url", DataType="normalizedString")]
    public string merchanturl {
        get {
            return this.merchanturlField;
        }
        set {
            this.merchanturlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name-on-card", DataType="normalizedString")]
    public string nameoncard {
        get {
            return this.nameoncardField;
        }
        set {
            this.nameoncardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-code", DataType="normalizedString")]
    public string authcode {
        get {
            return this.authcodeField;
        }
        set {
            this.authcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("auth-timestamp")]
    public System.DateTime authtimestamp {
        get {
            return this.authtimestampField;
        }
        set {
            this.authtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("card-type")]
    public CcType cardtype {
        get {
            return this.cardtypeField;
        }
        set {
            this.cardtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("charge-amount")]
    public decimal chargeamount {
        get {
            return this.chargeamountField;
        }
        set {
            this.chargeamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transaction-type", DataType="normalizedString")]
    public string transactiontype {
        get {
            return this.transactiontypeField;
        }
        set {
            this.transactiontypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
[System.Xml.Serialization.XmlRootAttribute("shipment-refund-request", Namespace="http://www.canadapost.ca/ws/shipment-v8", IsNullable=false)]
public partial class ShipmentRefundRequestType {
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.canadapost.ca/ws/shipment-v8")]
[System.Xml.Serialization.XmlRootAttribute("groups", Namespace="http://www.canadapost.ca/ws/shipment-v8", IsNullable=false)]
public partial class GroupsType {
    
    private GroupType[] groupField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("group")]
    public GroupType[] group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
}
